------------- 회원 생성
CREATE TABLE "MEMBER"(
	"MEMBER_NO" NUMBER PRIMARY KEY,
	"MEMBER_ID" VARCHAR2(50) NOT NULL, 
	"MEMBER_PW" VARCHAR2(100) NOT NULL,
	"MEMBER_NAME" VARCHAR2(50) NOT NULL,
	"MEMBER_GENDER" VARCHAR2(10) NOT NULL,
	"MEMBER_ADDRESS" VARCHAR2(100) NOT NULL,
	"MEMBER_DEL_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL
);
COMMENT ON COLUMN "MEMBER"."MEMBER_NO" IS '회원 번호(SEQ_MEMBER_NO)';

COMMENT ON COLUMN "MEMBER"."MEMBER_ID" IS '회원 아이디';

COMMENT ON COLUMN "MEMBER"."MEMBER_PW" IS '회원 비밀번호';

COMMENT ON COLUMN "MEMBER"."MEMBER_NAME" IS '회원 이름';

COMMENT ON COLUMN "MEMBER"."MEMBER_GENDER" IS '회원 성별';

COMMENT ON COLUMN "MEMBER"."MEMBER_ADDRESS" IS '회원 주소';

COMMENT ON COLUMN "MEMBER"."MEMBER_DEL_FL" IS '탈퇴여부(N:탈퇴X, Y: 탈퇴O)';

-- 탈퇴여부 CHECK 제약 조건
ALTER TABLE "MEMBER" ADD CONSTRAINT "CH_MEMBER_DEL_FL" 
CHECK("MEMBER_DEL_FL" IN ('N', 'Y'));

CREATE SEQUENCE SEQ_MEMBER NOCACHE;

-- 회원 객체 생성
INSERT INTO "MEMBER"
VALUES(SEQ_MEMBER.NEXTVAL, 'user01', 'pass01'
	, '유저일','여','서울시 서대문구 홍제1동 동일빌라트b동202호',DEFAULT);

INSERT INTO "MEMBER"
VALUES
(SEQ_MEMBER.NEXTVAL, 'user02', 'pass02', '유저이','남','서울시 은평구 연신내1동 동일빌라트a동202호',DEFAULT);
	
COMMIT;

----------------- 책 생성

CREATE TABLE BOOK(
	BOOK_NO NUMBER PRIMARY KEY,
	BOOK_TITLE VARCHAR2(100) NOT NULL,
	BOOK_AUTHOR VARCHAR2(100) NOT NULL,
	PRICE NUMBER DEFAULT 0, 
	PUBLISHER VARCHAR2(100) NOT NULL
);

COMMENT ON COLUMN BOOK.BOOK_NO IS '책번호';
COMMENT ON COLUMN BOOK.BOOK_TITLE IS '도서제목';
COMMENT ON COLUMN BOOK.BOOK_AUTHOR IS '저자';
COMMENT ON COLUMN BOOK.PRICE IS '가격';
COMMENT ON COLUMN BOOK.PUBLISHER IS '출판사';

CREATE SEQUENCE BOOK_SEQ NOCACHE;

INSERT INTO BOOK VALUES(
BOOK_SEQ.NEXTVAL, '노인과 바다','헤밍웨이',7110,'현대시문학');

INSERT INTO BOOK VALUES (
BOOK_SEQ.NEXTVAL, '해리포터와 마법사의 돌', '조앤 K.롤링', 8100, '문학수첩');

INSERT INTO BOOK 
VALUES (BOOK_SEQ.NEXTVAL, '당신,거기 있어 줄래요?', '기욤 뮈소', 9450, '밝은세상');

INSERT INTO BOOK
VALUES (BOOK_SEQ.NEXTVAL, '종이 여자', '기욤 뮈소', 10850, '밝은세상');

INSERT INTO BOOK
VALUES (BOOK_SEQ.NEXTVAL, '금단의 마술', '히가시노 게이고', 16920, '재인');

COMMIT;
	
-------------------- 주문 정보 테이블
CREATE TABLE ORDERS(
		ORDER_NO NUMBER PRIMARY KEY,
		BOOK_NO NUMBER REFERENCES "BOOK" ON DELETE CASCADE,
		MEMBER_NO NUMBER REFERENCES "MEMBER" ON DELETE CASCADE,
		ORDER_DATE DATE DEFAULT SYSDATE,
		ORDER_QUANTITY NUMBER DEFAULT 0, 
		STATUS CHAR(1)  DEFAULT 'N' CHECK(STATUS IN('Y','N'))
);
COMMENT ON COLUMN ORDERS.ORDER_NO IS '주문번호';
COMMENT ON COLUMN ORDERS.BOOK_NO IS '책번호';
COMMENT ON COLUMN ORDERS.MEMBER_NO IS '회원번호';
COMMENT ON COLUMN ORDERS.ORDER_DATE IS '주문일';
COMMENT ON COLUMN ORDERS.ORDER_QUANTITY IS '주문수량';
COMMENT ON COLUMN ORDERS.STATUS IS '처리상태';

CREATE SEQUENCE SEQ_ORDER_NO;

INSERT INTO ORDERS VALUES(
SEQ_ORDER_NO.NEXTVAL,SEQ_ORDER_NO.NEXTVAL,SEQ_ORDER_NO.NEXTVAL,SYSDATE, DEFAULT, 'N'
);

COMMIT;

----------- 조회 모음

SELECT * FROM "MEMBER";
SELECT * FROM "BOOK";
SELECT * FROM "ORDERS";

------- 삭제 모음

DROP SEQUENCE SEQ_MEMBER;
DROP SEQUENCE BOOK_SEQ;
DROP SEQUENCE SEQ_ORDER_NO;
DROP TABLE ORDERS;
DROP TABLE BOOK;
DROP TABLE "MEMBER";